stash:
  build: docker/stash
  ports:
    - "7990:7990" # no cache
    - "7999:7999" # ssh port
  links:
    - database
  volumes:
    - home:/opt/stash-home
  restart: no

database:
  build: docker/postgres
  volumes:
    - tmp:/tmp # import backups
  restart: no
